const opportunitiesData = [
  {
    id: 1,
    name: "IT & Technology",
    icon: "💻",
    description: "Technology, software and digital career opportunities",
    jobs: [
      "Software Developer",
      "Web Developer",
      "App Developer",
      "Data Analyst",
      "Cybersecurity",
      "IT Support",
      "QA/Testing",
      "UI/UX Designer",
      "DevOps",
      "AI/ML",
    ],
  },

  {
    id: 2,
    name: "Healthcare",
    icon: "🏥",
    description: "Healthcare, medical and patient-care opportunities",
    jobs: [
      "Doctor",
      "Nurse",
      "Pharmacist",
      "Lab Technician",
      "Medical Assistant",
      "Receptionist",
      "Hospital Admin",
      "Caregiver",
      "Physiotherapist",
    ],
  },

  {
    id: 3,
    name: "Construction & Skilled Trades",
    icon: "🏗️",
    description: "Skilled trade and construction opportunities",
    jobs: [
      "Electrician",
      "Plumber",
      "Carpenter",
      "Welder",
      "Painter",
      "Mason",
      "HVAC Technician",
      "Machine Operator",
      "Construction Worker",
    ],
  },

  {
    id: 4,
    name: "Transport & Logistics",
    icon: "🚚",
    description: "Driving, delivery, logistics and warehouse opportunities",
    jobs: [
      "Driver",
      "Delivery Partner",
      "Truck Driver",
      "Warehouse Worker",
      "Logistics Executive",
      "Courier",
      "Fleet Manager",
      "Loading/Unloading",
    ],
  },

  {
    id: 5,
    name: "Hospitality & Tourism",
    icon: "🏨",
    description: "Hotels, restaurants, travel and tourism opportunities",
    jobs: [
      "Hotel Staff",
      "Chef",
      "Cook",
      "Waiter",
      "Housekeeping",
      "Receptionist",
      "Security",
      "Travel Agent",
      "Tour Guide",
    ],
  },

  {
    id: 6,
    name: "Retail & Sales",
    icon: "🛒",
    description: "Retail, sales, customer service and business opportunities",
    jobs: [
      "Sales Executive",
      "Store Manager",
      "Cashier",
      "Retail Associate",
      "Business Development",
      "Telecaller",
      "Customer Support",
      "Field Sales",
    ],
  },

  {
    id: 7,
    name: "Manufacturing",
    icon: "🏭",
    description: "Factory, production and industrial opportunities",
    jobs: [
      "Factory Worker",
      "Machine Operator",
      "Production Supervisor",
      "Quality Inspector",
      "Maintenance Technician",
      "Assembly Worker",
      "Packaging Worker",
    ],
  },

  {
    id: 8,
    name: "Agriculture",
    icon: "🌾",
    description: "Farming, agriculture, dairy and food-processing opportunities",
    jobs: [
      "Farm Worker",
      "Agricultural Technician",
      "Farm Manager",
      "Dairy Worker",
      "Poultry Worker",
      "Tractor Operator",
      "Food Processing Worker",
    ],
  },

  {
    id: 9,
    name: "Education",
    icon: "🎓",
    description: "Teaching, training and educational opportunities",
    jobs: [
      "Teacher",
      "Professor",
      "Tutor",
      "Trainer",
      "Teaching Assistant",
      "School Administrator",
      "Online Tutor",
    ],
  },

  {
    id: 10,
    name: "Finance & Banking",
    icon: "🏦",
    description: "Banking, accounting, finance and insurance opportunities",
    jobs: [
      "Accountant",
      "Bank Clerk",
      "Financial Advisor",
      "Insurance Agent",
      "Loan Officer",
      "Banking Operations",
      "Auditor",
      "Tax Assistant",
    ],
  },

  {
    id: 11,
    name: "Government & Public Sector",
    icon: "🏛️",
    description: "Government, public-sector and administrative opportunities",
    jobs: [
      "Government Jobs",
      "Public-sector Jobs",
      "Municipal Jobs",
      "Police",
      "Defence",
      "Railways",
      "Postal Jobs",
      "Administrative Positions",
    ],
  },

  {
    id: 12,
    name: "Creative & Media",
    icon: "🎨",
    description: "Design, photography, media and creative opportunities",
    jobs: [
      "Graphic Designer",
      "Photographer",
      "Video Editor",
      "Content Creator",
      "Animator",
      "Social Media Manager",
      "Writer",
      "Makeup Artist",
    ],
  },

  {
    id: 13,
    name: "Domestic & Service Jobs",
    icon: "🧹",
    description: "Domestic, personal care and everyday service opportunities",
    jobs: [
      "Housekeeping",
      "Cook",
      "Babysitter",
      "Caregiver",
      "Cleaner",
      "Gardener",
      "Security Guard",
      "Driver",
      "Domestic Helper",
    ],
  },

  {
    id: 14,
    name: "Office & Administrative",
    icon: "🧑‍💼",
    description: "Office, administration, HR and support opportunities",
    jobs: [
      "Receptionist",
      "Office Assistant",
      "Data Entry",
      "HR Assistant",
      "Back Office Executive",
      "Office Manager",
      "Executive Assistant",
    ],
  },
];

export default opportunitiesData;